export const styles = {
  Box: {
    width: "100%",
    paddingTop: "80px",
    paddingBottom: "30px",
    backgroundColor: "secondary.main",
  },
  boxComingSoon: {
    width: "100%",
    paddingTop: "10px",
    paddingBottom: "30px",
    backgroundColor: "secondary.main",
  },
  container: {
    paddingBottom: "40px",
    display: "flex",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    margin: "auto",
  },
  img: {
    display: "flex",
    flexDirection: "row",
  },
  form: {
    alignItems: "center",
    textAlign: "center",
    width: "550px",
    margin: "auto",
    paddingBottom: "40px",
    display: "flex",
    flexDirection: "column",
    paddingTop: "25px",
  },
  formHeading: {
    fontWeight: "bold",
    color: "black",
  },
  formtext: {
    color: "grey",
  },
  inputForm: {
    padding: "5px",
    borderRadius: "5px",
    width: "100%",
    color: "black",
    marginTop: "20px",
  },
  inputFormT: {
    padding: "5px",
    borderRadius: "5px",
    width: "100%",
    color: "black",
    marginTop: "20px",
    border: "1px solid rgba(0, 0, 0, 0.4)",
  },
  buttonSubmit: {
    marginTop: "40px",
    width: "100%",
    textAlign: "center",
    fontWeight: "bold",
    background: "#16B1E1",
    height: "52px",
    "&:hover": {
      backgroundColor: "secondary.contrastText",
    },
  },
  tabsGrid: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  button: {
    Font: "Poppins",
    fontWeight: "500",
    fontSize: "16px",
    paddingTop: "8px",
    borderRadius: "19px",
    color: "white",
    LineHeight: "24px",
    margin: "auto",
    "&:hover": {
      backgroundColor: "White",
      color: "black",
    },
  },
  buttoncothercoutry: {
    Font: "Poppins",
    fontWeight: "500",
    fontSize: "16px",
    paddingTop: "8px",
    borderRadius: "19px",
    color: "white",
    LineHeight: "24px",
    margin: "auto",
    "&:hover": {
      backgroundColor: "White",
      color: "black",
    },
  },
  text1: {
    color: "white",
    paddingTop: "20px",
    textAlign: "center",
  },
  text2: {
    color: "white",
    paddingTop: "15px",
    textAlign: "center",
  },
  div: {
    display: "flex",
    columnGap: "10px",
  },
};
