export const itemData = [
  {
    heading: "Our Team",
    title: "Life At Gsoft",
    discription:
      "We are providing professional services of Website Development as well as Mobile App Development to Enterprises and companies. Global Software Consulting intends to be in front of the client’s needs and delivers modern solutions for modern problems of the client's business from the initial phase of scoping the requirements up to the final delivery, maintenance, and continuous upgrade.",
    rows: 2,
    cols: 2,
    mobilecols: 4,
  },
  {
    img: "/images/lag1.png",
    title: "Coffee",
    rows: 2,
    cols: 2,
    mobilecols: 4,
  },
  {
    img: "/images/lag2.png",
    title: "Honey",
    author: "@arwinneil",
    rows: 4,
    cols: 2,
    mobilecols: 4,
  },
  {
    img: "/images/lag3.png",
    title: "Hats",
    cols: 2,
    rows: 2,
    mobilecols: 4,
  },
  {
    img: "/images/lag4.png",
    title: "Basketball",
    rows: 2,
    mobilecols: 2,
  },
  {
    img: "/images/lag5.png",
    title: "Fern",
    rows: 2,
    mobilecols: 2,
  },
  {
    img: "/images/lag6.png",
    title: "Breakfast",
    rows: 2,
    cols: 2,
    mobilecols: 2,
  },
  {
    img: "/images/lag7.png",
    title: "Coffee",
    rows: 2,
    cols: 2,
    mobilecols: 2,
  },
  {
    img: "/images/lag5.png",
    title: "Mushrooms",
    rows: 2,
    cols: 2,
    mobilecols: 2,
  },
  {
    img: "/images/lag8.png",
    title: "Mushrooms",
    rows: 2,
    cols: 2,
    mobilecols: 2,
  },
  {
    img: "/images/lag2.png",
    title: "Honey",
    author: "@arwinneil",
    rows: 4,
    cols: 2,
    mobilecols: 4,
  },
  {
    img: "/images/lag3.png",
    title: "Hats",
    cols: 2,
    rows: 2,
    mobilecols: 4,
  },
  {
    img: "/images/lag4.png",
    title: "Basketball",
    rows: 2,
    mobilecols: 2,
  },
  {
    img: "/images/lag5.png",
    title: "Fern",
    rows: 2,
    mobilecols: 2,
  },
];
