export const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: "20px",
    paddingBottom: "20px",
    paddingLeft: "20px",
    paddingRight: "20px",
    marginBottom: "8%",
  },
  searchgrid: {
    display: "flex",
    marginTop: "30px",
  },
  searchInputcity: {
    height: "60px",
    width: "310px",
    display: "flex",
  },
  searchInput: {
    borderRadius: "5px",
    height: "57px",
    width: { xs: "100%", sm: "30%" },
    display: "flex",
    justifyContent: "center",
    alignSelf: "flex-start",
    border: "1.5px solid #C0C0C0",
  },
  selectFeild: {
    borderRadius: "5px",
    height: "57px",
    width: { xs: "100%", sm: "30%" },
    display: "flex",
    justifyContent: "center",
    alignSelf: "flex-start",
  },
  cardBo: {
    display: "flex",
    flexDirection: "row",
    justifyContent: { xs: "center", sm: "flex-start", lg: "flex-start" },
    marginTop: "10px",
    marginBottom: "20px",
    boxShadow: "  #6C6C6C0D",
    borderRight: "8px",
    alignItems: "center",
    paddingTop: "80px",
  },
  cardHeading: {
    margin: "10px",
  },
  cityHeading: {
    margin: "10px",
  },
  cardsubapply: {
    color: "secondary.main",
    paddingTop: "1px",
  },
  cardIcon: {
    height: "20px",
    width: "43px",
    display: "flex",
    justifyContent: "center",
    color: "secondary.contrastText",
  },
  cardIcon2: {
    height: "20px",
    width: "43px",
  },
  cardsubHeading: {
    margin: "10px",
    color: "success.light",
  },
  cardBox: {
    height: "300px",
    borderRadius: "10px",
    width: "330px",
    justifyContent: "center",
    margin: "15px",
    alignItems: "center",
    boxShadow: 1,
  },
  cardBoxapply: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: "10px",
    cursor: "pointer",
  },
  cardBoxmarketing: {
    display: "flex",
    alignItems: "center",
    paddingTop: "5px",
  },
  cardsubapplybox3: {
    color: "success.contrastText",
    borderRight: "1px solid #7E7E7E",
    display: "flex",
    justifyContent: "center",
    width: "80px",
    alignItems: "center",
    height: "10px",
  },
  cardsubapplybox4: {
    color: "success.contrastText",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "10px",
  },
};
