export const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: "secondary.light",
    backgroundSize: "cover",
    backgroundColor: "secondary.main",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    paddingTop: "150px",
  },
  block: {
    paddingLeft: "20px",
    paddingRight: "20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    justifyContent: "center",
    marginTop: "5px",
    marginBottom: "150px",
  },
};
